version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: getmefixed-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/getmefixed?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    networks:
      - getmefixed-network

  postgres:
    image: postgres:14
    container_name: getmefixed-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=getmefixed
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - getmefixed-network

  redis:
    image: redis:alpine
    container_name: getmefixed-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - getmefixed-network

networks:
  getmefixed-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: