export const ERROR_CODES = {
    INVALID_LICENSE: 'INVALID_LICENSE',
    LICENSE_EXPIRED: 'LICENSE_EXPIRED',
    LICENSE_REVOKED: 'LICENSE_REVOKED',
    NO_TOKENS: 'NO_TOKENS',
    PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
    INVALID_PLUGIN_VERSION: 'INVALID_PLUGIN_VERSION',
  } as const;